FROM docker.io/library/ubuntu:18.04

# System packages
COPY ./conf/ubuntu-sources-hk.list /etc/apt/sources.list
#COPY ./conf/proxy.conf /etc/apt/apt.conf.d/proxy.conf
RUN apt update && apt-get update
RUN apt clean && apt-get clean 
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip net-tools vim curl wget unzip procps ssh sudo 
RUN apt-get install -y libk5crypto3 libkrb5-3 libsqlite3-0
RUN apt-get install -y openjdk-8-jdk libpostgresql-jdbc-java && \
  ln -sf /usr/bin/python3 /usr/bin/python && \
  rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install iputils-ping -y
RUN pip3 install wget requests datawrangler


## Install Python 3.7
RUN apt-get clean && apt-get update -y
RUN apt-get install --reinstall python3-apt -y
RUN apt-get install software-properties-common -y
RUN add-apt-repository 'ppa:deadsnakes/ppa' -y 
RUN apt install python3.7 -y
RUN ln -sf /usr/bin/python3.7 /usr/bin/python3

## set insecure curl 
RUN echo "-k" >>  ~/.curlrc
